###
POST http://localhost:9000/api/cadastro HTTP/1.1
Content-Type: application/json

[{
    "nome_card": "bulbasaur",
      "attribute": {
      "hp": 45,
      "attack": 49,
      "defense": 49,
      "special-attack": 65,
      "special-defense": 65,
      "speed": 45}
    }
]

###
GET http://localhost:9000/api/lista HTTP/1.1
Content-Type: application/json



###
GET http://localhost:9000/api/get/4 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:9000/api/update/4 HTTP/1.1
Content-Type: application/json

{
     "nome_card": "charmander"
}


###
DELETE http://localhost:9000/api/delete/4 HTTP/1.1
Content-Type: application/json
